package slaydemo.backend.battle

package object objects {
  export slaydemo.backend.battle.objects.core.AmmoCount
  export slaydemo.backend.battle.objects.core.BattleAggregateState
  export slaydemo.backend.battle.objects.core.BattleCapacity
  export slaydemo.backend.battle.objects.core.BattleEventId
  export slaydemo.backend.battle.objects.core.BattleHighlightLine
  export slaydemo.backend.battle.objects.core.BattleId
  export slaydemo.backend.battle.objects.core.BattleMapLabel
  export slaydemo.backend.battle.objects.core.BattleModeLabel
  export slaydemo.backend.battle.objects.core.BattlePlacement
  export slaydemo.backend.battle.objects.core.BattlePlayersLine
  export slaydemo.backend.battle.objects.core.BattleResultId
  export slaydemo.backend.battle.objects.core.BattleResultLabel
  export slaydemo.backend.battle.objects.core.BattleTick
  export slaydemo.backend.battle.objects.core.BattleTimelineHint
  export slaydemo.backend.battle.objects.core.BattleVector2
  export slaydemo.backend.battle.objects.core.ClientCommandSeq
  export slaydemo.backend.battle.objects.core.CooldownMillis
  export slaydemo.backend.battle.objects.core.Damage
  export slaydemo.backend.battle.objects.core.DurationMillis
  export slaydemo.backend.battle.objects.core.ElapsedMillis
  export slaydemo.backend.battle.objects.core.EpochMillis
  export slaydemo.backend.battle.objects.core.FacingRadians
  export slaydemo.backend.battle.objects.core.HeroId
  export slaydemo.backend.battle.objects.core.HitPoints
  export slaydemo.backend.battle.objects.core.PickupId
  export slaydemo.backend.battle.objects.core.PlayerId
  export slaydemo.backend.battle.objects.core.ProjectileId
  export slaydemo.backend.battle.objects.core.QueueRequestId
  export slaydemo.backend.battle.objects.core.Radius
  export slaydemo.backend.battle.objects.core.Rating
  export slaydemo.backend.battle.objects.core.RatingDelta
  export slaydemo.backend.battle.objects.core.RoomId
  export slaydemo.backend.battle.objects.core.Score
  export slaydemo.backend.battle.objects.core.SeatIndex
  export slaydemo.backend.battle.objects.core.SlowFieldId
  export slaydemo.backend.battle.objects.core.SpawnPointIndex
  export slaydemo.backend.battle.objects.core.Stamina
  export slaydemo.backend.battle.objects.core.TicketId
  export slaydemo.backend.battle.objects.event.BattleEventParticipant
  export slaydemo.backend.battle.objects.event.BattleEventState
  export slaydemo.backend.battle.objects.pickup.BattlePickupAvailability
  export slaydemo.backend.battle.objects.pickup.BattlePickupState
  export slaydemo.backend.battle.objects.player.BattleParticipantKind
  export slaydemo.backend.battle.objects.player.BattlePlayerLifeState
  export slaydemo.backend.battle.objects.player.BattlePlayerSkillState
  export slaydemo.backend.battle.objects.player.BattlePlayerState
  export slaydemo.backend.battle.objects.player.BattleSurvivalOutcome
  export slaydemo.backend.battle.objects.projectile.BattleProjectileState
  export slaydemo.backend.battle.objects.projectile.BattleProjectileTerminalState
  export slaydemo.backend.battle.objects.queue.BattleQueueParticipant
  export slaydemo.backend.battle.objects.queue.BattleQueueSnapshot
  export slaydemo.backend.battle.objects.queue.BattleSessionBootstrap
  export slaydemo.backend.battle.objects.queue.BattleSessionBootstrapSeat
  export slaydemo.backend.battle.objects.queue.BattleSessionDescriptor
  export slaydemo.backend.battle.objects.queue.BattleSessionRosterEntry
  export slaydemo.backend.battle.objects.queue.RealtimeRoomSnapshot
  export slaydemo.backend.battle.objects.replay.BattleReplayFrameState
  export slaydemo.backend.battle.objects.replay.BattleReplayHeroFrameState
  export slaydemo.backend.battle.objects.replay.BattleReplayHeroLifeState
  export slaydemo.backend.battle.objects.replay.BattleReplayPickupFrameState
  export slaydemo.backend.battle.objects.replay.BattleReplayProjectileFrameState
  export slaydemo.backend.battle.objects.result.BattleResultRecord
  export slaydemo.backend.battle.objects.skill.BattleCommandSkillIntents
  export slaydemo.backend.battle.objects.skill.BattleSlowFieldState
  export slaydemo.backend.battle.objects.weapon.BattleWeaponState
  export slaydemo.backend.battle.objects.weapon.BattleWeaponSwitchDirection
  export slaydemo.backend.battle.objects.weapon.BattleWeaponSwitchIndex
  export slaydemo.backend.battle.objects.weapon.BattleWeaponThermalState
}
