package services.battle

package object services {
  export _root_.services.battle.engine.BattleEngine
  export _root_.services.battle.engine.BattlePickupCatalog
  export _root_.services.battle.engine.BattlePickupDefinition
  export _root_.services.battle.engine.BattlePickupRules
  export _root_.services.battle.engine.BattleSkillCatalog
  export _root_.services.battle.engine.BattleSkillCommandRules
  export _root_.services.battle.engine.BattleSkillRules
  export _root_.services.battle.engine.BattleSlowFieldRuntimeRules
  export _root_.services.battle.engine.BattleBotCatalog
  export _root_.services.battle.engine.BattleBotMoveSpeed
  export _root_.services.battle.engine.BattleBotRules
  export _root_.services.battle.engine.BattleInputRules
  export _root_.services.battle.engine.BattlePlayerLifecycleRules
  export _root_.services.battle.engine.BattlePlayerRuntimeRules
  export _root_.services.battle.engine.BattleHeldFireRuntimeRules
  export _root_.services.battle.engine.BattleProjectileFactoryRules
  export _root_.services.battle.engine.BattleProjectileImpactRules
  export _root_.services.battle.engine.BattleProjectileMotionRules
  export _root_.services.battle.engine.BattleProjectileRuntimeRules
  export _root_.services.battle.engine.BattleProjectileTargetingRules
  export _root_.services.battle.engine.BattleProjectileTerminalRules
  export _root_.services.battle.engine.BattleWeaponCatalog
  export _root_.services.battle.engine.BattleWeaponFireDefinition
  export _root_.services.battle.engine.BattleWeaponFireRules
  export _root_.services.battle.engine.BattleWeaponFiringResource
  export _root_.services.battle.engine.BattleWeaponHeat
  export _root_.services.battle.engine.BattleWeaponHeatDefinition
  export _root_.services.battle.engine.BattleWeaponHeatRatePerSecond
  export _root_.services.battle.engine.BattleWeaponInventoryDefinition
  export _root_.services.battle.engine.BattleWeaponProjectileCount
  export _root_.services.battle.engine.BattleWeaponProjectileDefinition
  export _root_.services.battle.engine.BattleWeaponProjectileSpeed
  export _root_.services.battle.engine.BattleWeaponRecoilStrength
  export _root_.services.battle.engine.BattleWeaponRules
  export _root_.services.battle.services.queue.BattleQueueHeartbeatRules
  export _root_.services.battle.services.queue.BattleQueueIdAllocator
  export _root_.services.battle.services.queue.BattleQueueJoinAuthorizationError
  export _root_.services.battle.services.queue.BattleQueueJoinAuthorizationService
  export _root_.services.battle.services.queue.BattleQueueJoinCommand
  export _root_.services.battle.services.queue.BattleQueueJoinDraft
  export _root_.services.battle.services.queue.BattleQueueJoinRules
  export _root_.services.battle.services.queue.BattleQueueLeaveOutcome
  export _root_.services.battle.services.queue.BattleQueueLeaveRules
  export _root_.services.battle.services.queue.BattleQueueLeaveTransition
  export _root_.services.battle.services.queue.BattleQueueParticipantRules
  export _root_.services.battle.services.queue.BattleQueueRequestReuseResult
  export _root_.services.battle.services.queue.BattleQueueRequestReuseRules
  export _root_.services.battle.services.queue.BattleQueueRoomLifecycleRules
  export _root_.services.battle.services.queue.BattleQueueRoomSelectionRules
  export _root_.services.battle.services.queue.BattleQueueService
  export _root_.services.battle.services.queue.BattleQueueSessionLookupRules
  export _root_.services.battle.services.queue.BattleQueueSnapshots
  export _root_.services.battle.services.queue.BattleQueueStatusError
  export _root_.services.battle.services.queue.BattleQueueTicketSnapshots
  export _root_.services.battle.services.queue.BattleRoomBootstrapParticipant
  export _root_.services.battle.services.queue.BattleRoomBootstrapper
  export _root_.services.battle.services.queue.BattleRoomError
  export _root_.services.battle.services.queue.BattleRoomLifecycleSink
  export _root_.services.battle.services.queue.DefaultBattleQueueJoinAuthorizationService
  export _root_.services.battle.services.queue.InMemoryBattleQueueService
  export _root_.services.battle.services.queue.NoopBattleRoomLifecycleSink
  export _root_.services.battle.services.queue.QueueParticipantEntry
  export _root_.services.battle.services.queue.QueueRoom
  export _root_.services.battle.services.queue.RealtimeRoomHeartbeatCommand
  export _root_.services.battle.services.queue.TicketRecord
  export _root_.services.battle.services.results.BattleFinishProjectionArtifactWriter
  export _root_.services.battle.services.results.BattleFinishProjectionCompletionRules
  export _root_.services.battle.services.results.BattleFinishProjectionFailureReporter
  export _root_.services.battle.services.results.BattleFinishProjectionLabelRules
  export _root_.services.battle.services.results.BattleFinishProjectionMailFactory
  export _root_.services.battle.services.results.BattleFinishProjectionOutcome
  export _root_.services.battle.services.results.BattleFinishProjectionPlan
  export _root_.services.battle.services.results.BattleFinishProjectionPlanner
  export _root_.services.battle.services.results.BattleFinishProjectionPlayerRules
  export _root_.services.battle.services.results.BattleFinishProjectionPreparation
  export _root_.services.battle.services.results.BattleFinishProjectionPreparationRules
  export _root_.services.battle.services.results.BattleFinishProjectionReplayRules
  export _root_.services.battle.services.results.BattleFinishProjectionStatus
  export _root_.services.battle.services.results.BattleFinishProjectionStatusRules
  export _root_.services.battle.services.results.BattleFinishProjectionTimeRules
  export _root_.services.battle.services.results.BattleFinishProjector
  export _root_.services.battle.engine.BattleHistoryCatalog
  export _root_.services.battle.engine.BattleHistoryCount
  export _root_.services.battle.services.results.BattlePreviousRatings
  export _root_.services.battle.services.results.BattleProjectionArtifactWriteOutcome
  export _root_.services.battle.services.results.BattleReplayFallbackTimeline
  export _root_.services.battle.engine.BattleReplayFrameRecorder
  export _root_.services.battle.services.results.BattleReplayFramesJson
  export _root_.services.battle.services.results.BattleReplayFramesJsonRenderer
  export _root_.services.battle.services.results.BattleReplayFrameTimelineRules
  export _root_.services.battle.services.results.BattleReplayProjectionArtifactWriter
  export _root_.services.battle.services.results.BattleResultProjectionArtifactWriter
  export _root_.services.battle.services.results.BattleResultRecordCommand
  export _root_.services.battle.services.results.BattleResultRecordError
  export _root_.services.battle.services.results.BattleResultService
  export _root_.services.battle.services.results.BattleSettlement
  export _root_.services.battle.services.results.BattleSettlementBuildContext
  export _root_.services.battle.services.results.BattleSettlementScoringRules
  export _root_.services.battle.services.results.ConsoleBattleFinishProjectionFailureReporter
  export _root_.services.battle.services.results.DefaultBattleFinishProjector
  export _root_.services.battle.services.results.DefaultBattleResultService
  export _root_.services.battle.services.results.InMemoryBattleResultService
  export _root_.services.battle.services.results.NoopBattleFinishProjector
  export _root_.services.battle.engine.BattleAggregateUpdateRules
  export _root_.services.battle.engine.BattleEventFactory
  export _root_.services.battle.engine.BattleRetentionRules
  export _root_.services.battle.engine.BattleRuntimeCatalog
  export _root_.services.battle.engine.BattleRuntimeFinalizationRules
  export _root_.services.battle.engine.BattleRuntimeFinishRules
  export _root_.services.battle.engine.BattleRuntimeStepRules
  export _root_.services.battle.engine.BattleTimeRules
  export _root_.services.battle.services.session.BattleCommandAcceptanceFactory
  export _root_.services.battle.engine.BattleCommandApplicationRules
  export _root_.services.battle.services.session.BattleCommandOwnership
  export _root_.services.battle.services.session.BattleCommandSubmitError
  export _root_.services.battle.services.session.BattleFailureMessageFormatter
  export _root_.services.battle.services.session.BattleIdGenerator
  export _root_.services.battle.services.session.BattleRoomFinishedNotification
  export _root_.services.battle.services.session.BattleSessionLookup
  export _root_.services.battle.services.session.BattleSessionSeed
  export _root_.services.battle.services.session.BattleSessionStateFactory
  export _root_.services.battle.services.session.BattleStateReadError
  export _root_.services.battle.services.session.BattleStateService
  export _root_.services.battle.services.session.BattleStoredBattleAdvanceResult
  export _root_.services.battle.services.session.BattleStoredBattleAdvanceRules
  export _root_.services.battle.services.session.BattleStoredBattleInitializationRules
  export _root_.services.battle.services.session.CommandSubmission
  export _root_.services.battle.services.session.InMemoryBattleStateService
  export _root_.services.battle.services.session.RandomBattleIdGenerator
  export _root_.services.battle.services.session.StateRead
  export _root_.services.battle.services.session.StoredBattle
  export _root_.services.battle.engine.ArenaObstacle
  export _root_.services.battle.engine.ArenaObstacleKind
  export _root_.services.battle.engine.BattleArenaCatalog
  export _root_.services.battle.engine.BattleArenaCollision
  export _root_.services.battle.engine.BattleGeometry
  export _root_.services.battle.engine.BattleInitialLayout
  export _root_.services.battle.engine.BattleMotionRules
  export _root_.services.battle.engine.BattleMovementCatalog
  export _root_.services.battle.engine.BattleMovementSpeed
  export _root_.services.battle.engine.BattleSlowFactor
  export _root_.services.battle.engine.BattleStaminaRatePerSecond
}
