package services.battle

package object objects {
  export _root_.services.battle.objects.core.AmmoCount
  export _root_.services.battle.objects.core.BattleAggregateState
  export _root_.services.battle.objects.core.BattleCapacity
  export _root_.services.battle.objects.core.BattleEventId
  export _root_.services.battle.objects.core.BattleHighlightLine
  export _root_.services.battle.objects.core.BattleId
  export _root_.services.battle.objects.core.BattleMapId
  export _root_.services.battle.objects.core.BattleMapLabel
  export _root_.services.battle.objects.core.BattleModeLabel
  export _root_.services.battle.objects.core.BattlePlacement
  export _root_.services.battle.objects.core.BattlePlayersLine
  export _root_.services.battle.objects.core.BattleResultId
  export _root_.services.battle.objects.core.BattleResultLabel
  export _root_.services.battle.objects.core.BattleTick
  export _root_.services.battle.objects.core.BattleTimelineHint
  export _root_.services.battle.objects.core.BattleVector2
  export _root_.services.battle.objects.core.ClientCommandSeq
  export _root_.services.battle.objects.core.CooldownMillis
  export _root_.services.battle.objects.core.Damage
  export _root_.services.battle.objects.core.DurationMillis
  export _root_.services.battle.objects.core.ElapsedMillis
  export _root_.services.battle.objects.core.EpochMillis
  export _root_.services.battle.objects.core.FacingRadians
  export _root_.services.battle.objects.core.HeroId
  export _root_.services.battle.objects.core.HitPoints
  export _root_.services.battle.objects.core.PickupId
  export _root_.services.battle.objects.core.PlayerId
  export _root_.services.battle.objects.core.ProjectileId
  export _root_.services.battle.objects.core.QueueRequestId
  export _root_.services.battle.objects.core.Radius
  export _root_.services.battle.objects.core.Rating
  export _root_.services.battle.objects.core.RatingDelta
  export _root_.services.battle.objects.core.RoomId
  export _root_.services.battle.objects.core.Score
  export _root_.services.battle.objects.core.SeatIndex
  export _root_.services.battle.objects.core.SlowFieldId
  export _root_.services.battle.objects.core.SpawnPointIndex
  export _root_.services.battle.objects.core.Stamina
  export _root_.services.battle.objects.core.TicketId
  export _root_.services.battle.objects.command.BattleCommandAccepted
  export _root_.services.battle.objects.command.BattleCommandRequest
  export _root_.services.battle.objects.command.BattleCommandSkillOutcome
  export _root_.services.battle.objects.command.BattleCommandVector
  export _root_.services.battle.objects.event.BattleEventParticipant
  export _root_.services.battle.objects.event.BattleEventState
  export _root_.services.battle.objects.pickup.BattlePickupAvailability
  export _root_.services.battle.objects.pickup.BattlePickupState
  export _root_.services.battle.objects.player.BattleParticipantKind
  export _root_.services.battle.objects.player.BattlePlayerLifeState
  export _root_.services.battle.objects.player.BattlePlayerSkillState
  export _root_.services.battle.objects.player.BattlePlayerState
  export _root_.services.battle.objects.player.BattleSurvivalOutcome
  export _root_.services.battle.objects.projectile.BattleProjectileState
  export _root_.services.battle.objects.projectile.BattleProjectileTerminalState
  export _root_.services.battle.objects.queue.BattleQueueParticipant
  export _root_.services.battle.objects.queue.BattleQueueSnapshot
  export _root_.services.battle.objects.queue.BattleSessionBootstrap
  export _root_.services.battle.objects.queue.BattleSessionBootstrapSeat
  export _root_.services.battle.objects.queue.BattleSessionDescriptor
  export _root_.services.battle.objects.queue.BattleSessionRosterEntry
  export _root_.services.battle.objects.queue.RealtimeRoomSnapshot
  export _root_.services.battle.objects.replay.BattleReplayFrameState
  export _root_.services.battle.objects.replay.BattleReplayHeroFrameState
  export _root_.services.battle.objects.replay.BattleReplayHeroLifeState
  export _root_.services.battle.objects.replay.BattleReplayPickupFrameState
  export _root_.services.battle.objects.replay.BattleReplayProjectileFrameState
  export _root_.services.battle.objects.result.BattleResultRecord
  export _root_.services.battle.objects.skill.BattleCommandSkillIntents
  export _root_.services.battle.objects.skill.BattleSlowFieldState
  export _root_.services.battle.objects.weapon.BattleWeaponState
  export _root_.services.battle.objects.weapon.BattleWeaponSwitchDirection
  export _root_.services.battle.objects.weapon.BattleWeaponSwitchIndex
  export _root_.services.battle.objects.weapon.BattleWeaponThermalState
}
