export const AUTHORITATIVE_STATE_POLL_INTERVAL_MS = 100;
export const AUTHORITATIVE_COMMAND_UPLINK_INTERVAL_MS = 50;
export const AUTHORITATIVE_BOOTSTRAP_RETRY_MS = 150;
export const AUTHORITATIVE_RESULT_READY_RETRY_MS = 250;
export const AUTHORITATIVE_RESULT_READY_TIMEOUT_MS = 5_000;
export const ACTIVE_SESSION_PERSIST_INTERVAL_MS = 5_000;
export const VISITOR_BATTLE_BLOCKED_MESSAGE = "请先登录正式账号，Visitor/未登录状态不能进入正式匹配或开战。";
