package slaydemo.backend.battle

package object services {
  export slaydemo.backend.battle.services.abilities.BattlePickupCatalog
  export slaydemo.backend.battle.services.abilities.BattlePickupDefinition
  export slaydemo.backend.battle.services.abilities.BattlePickupRules
  export slaydemo.backend.battle.services.abilities.BattleSkillCatalog
  export slaydemo.backend.battle.services.abilities.BattleSkillCommandRules
  export slaydemo.backend.battle.services.abilities.BattleSkillRules
  export slaydemo.backend.battle.services.abilities.BattleSlowFieldRuntimeRules
  export slaydemo.backend.battle.services.actors.BattleBotCatalog
  export slaydemo.backend.battle.services.actors.BattleBotMoveSpeed
  export slaydemo.backend.battle.services.actors.BattleBotRules
  export slaydemo.backend.battle.services.actors.BattleInputRules
  export slaydemo.backend.battle.services.actors.BattlePlayerLifecycleRules
  export slaydemo.backend.battle.services.actors.BattlePlayerRuntimeRules
  export slaydemo.backend.battle.services.combat.BattleHeldFireRuntimeRules
  export slaydemo.backend.battle.services.combat.BattleProjectileFactoryRules
  export slaydemo.backend.battle.services.combat.BattleProjectileImpactRules
  export slaydemo.backend.battle.services.combat.BattleProjectileMotionRules
  export slaydemo.backend.battle.services.combat.BattleProjectileRuntimeRules
  export slaydemo.backend.battle.services.combat.BattleProjectileTargetingRules
  export slaydemo.backend.battle.services.combat.BattleProjectileTerminalRules
  export slaydemo.backend.battle.services.combat.BattleWeaponCatalog
  export slaydemo.backend.battle.services.combat.BattleWeaponFireDefinition
  export slaydemo.backend.battle.services.combat.BattleWeaponFireRules
  export slaydemo.backend.battle.services.combat.BattleWeaponFiringResource
  export slaydemo.backend.battle.services.combat.BattleWeaponHeat
  export slaydemo.backend.battle.services.combat.BattleWeaponHeatDefinition
  export slaydemo.backend.battle.services.combat.BattleWeaponHeatRatePerSecond
  export slaydemo.backend.battle.services.combat.BattleWeaponInventoryDefinition
  export slaydemo.backend.battle.services.combat.BattleWeaponProjectileCount
  export slaydemo.backend.battle.services.combat.BattleWeaponProjectileDefinition
  export slaydemo.backend.battle.services.combat.BattleWeaponProjectileSpeed
  export slaydemo.backend.battle.services.combat.BattleWeaponRecoilStrength
  export slaydemo.backend.battle.services.combat.BattleWeaponRules
  export slaydemo.backend.battle.services.queue.BattleQueueHeartbeatRules
  export slaydemo.backend.battle.services.queue.BattleQueueIdAllocator
  export slaydemo.backend.battle.services.queue.BattleQueueJoinAuthorizationError
  export slaydemo.backend.battle.services.queue.BattleQueueJoinAuthorizationService
  export slaydemo.backend.battle.services.queue.BattleQueueJoinCommand
  export slaydemo.backend.battle.services.queue.BattleQueueJoinDraft
  export slaydemo.backend.battle.services.queue.BattleQueueJoinRules
  export slaydemo.backend.battle.services.queue.BattleQueueLeaveOutcome
  export slaydemo.backend.battle.services.queue.BattleQueueLeaveRules
  export slaydemo.backend.battle.services.queue.BattleQueueLeaveTransition
  export slaydemo.backend.battle.services.queue.BattleQueueParticipantRules
  export slaydemo.backend.battle.services.queue.BattleQueueRequestReuseResult
  export slaydemo.backend.battle.services.queue.BattleQueueRequestReuseRules
  export slaydemo.backend.battle.services.queue.BattleQueueRoomLifecycleRules
  export slaydemo.backend.battle.services.queue.BattleQueueRoomSelectionRules
  export slaydemo.backend.battle.services.queue.BattleQueueService
  export slaydemo.backend.battle.services.queue.BattleQueueSessionLookupRules
  export slaydemo.backend.battle.services.queue.BattleQueueSnapshots
  export slaydemo.backend.battle.services.queue.BattleQueueStatusError
  export slaydemo.backend.battle.services.queue.BattleQueueTicketSnapshots
  export slaydemo.backend.battle.services.queue.BattleRoomBootstrapParticipant
  export slaydemo.backend.battle.services.queue.BattleRoomBootstrapper
  export slaydemo.backend.battle.services.queue.BattleRoomError
  export slaydemo.backend.battle.services.queue.BattleRoomLifecycleSink
  export slaydemo.backend.battle.services.queue.DefaultBattleQueueJoinAuthorizationService
  export slaydemo.backend.battle.services.queue.InMemoryBattleQueueService
  export slaydemo.backend.battle.services.queue.NoopBattleRoomLifecycleSink
  export slaydemo.backend.battle.services.queue.QueueParticipantEntry
  export slaydemo.backend.battle.services.queue.QueueRoom
  export slaydemo.backend.battle.services.queue.RealtimeRoomHeartbeatCommand
  export slaydemo.backend.battle.services.queue.TicketRecord
  export slaydemo.backend.battle.services.results.BattleFinishProjectionArtifactWriter
  export slaydemo.backend.battle.services.results.BattleFinishProjectionCompletionRules
  export slaydemo.backend.battle.services.results.BattleFinishProjectionFailureReporter
  export slaydemo.backend.battle.services.results.BattleFinishProjectionLabelRules
  export slaydemo.backend.battle.services.results.BattleFinishProjectionMailFactory
  export slaydemo.backend.battle.services.results.BattleFinishProjectionOutcome
  export slaydemo.backend.battle.services.results.BattleFinishProjectionPlan
  export slaydemo.backend.battle.services.results.BattleFinishProjectionPlanner
  export slaydemo.backend.battle.services.results.BattleFinishProjectionPlayerRules
  export slaydemo.backend.battle.services.results.BattleFinishProjectionPreparation
  export slaydemo.backend.battle.services.results.BattleFinishProjectionPreparationRules
  export slaydemo.backend.battle.services.results.BattleFinishProjectionReplayRules
  export slaydemo.backend.battle.services.results.BattleFinishProjectionStatus
  export slaydemo.backend.battle.services.results.BattleFinishProjectionStatusRules
  export slaydemo.backend.battle.services.results.BattleFinishProjectionTimeRules
  export slaydemo.backend.battle.services.results.BattleFinishProjector
  export slaydemo.backend.battle.services.results.BattleHistoryCatalog
  export slaydemo.backend.battle.services.results.BattleHistoryCount
  export slaydemo.backend.battle.services.results.BattlePreviousRatings
  export slaydemo.backend.battle.services.results.BattleProjectionArtifactWriteOutcome
  export slaydemo.backend.battle.services.results.BattleReplayFallbackTimeline
  export slaydemo.backend.battle.services.results.BattleReplayFrameRecorder
  export slaydemo.backend.battle.services.results.BattleReplayFramesJson
  export slaydemo.backend.battle.services.results.BattleReplayFramesJsonRenderer
  export slaydemo.backend.battle.services.results.BattleReplayFrameTimelineRules
  export slaydemo.backend.battle.services.results.BattleReplayProjectionArtifactWriter
  export slaydemo.backend.battle.services.results.BattleResultProjectionArtifactWriter
  export slaydemo.backend.battle.services.results.BattleResultRecordCommand
  export slaydemo.backend.battle.services.results.BattleResultRecordError
  export slaydemo.backend.battle.services.results.BattleResultService
  export slaydemo.backend.battle.services.results.BattleSettlement
  export slaydemo.backend.battle.services.results.BattleSettlementBuildContext
  export slaydemo.backend.battle.services.results.BattleSettlementScoringRules
  export slaydemo.backend.battle.services.results.ConsoleBattleFinishProjectionFailureReporter
  export slaydemo.backend.battle.services.results.DefaultBattleFinishProjector
  export slaydemo.backend.battle.services.results.DefaultBattleResultService
  export slaydemo.backend.battle.services.results.InMemoryBattleResultService
  export slaydemo.backend.battle.services.results.NoopBattleFinishProjector
  export slaydemo.backend.battle.services.runtime.BattleAggregateUpdateRules
  export slaydemo.backend.battle.services.runtime.BattleEventFactory
  export slaydemo.backend.battle.services.runtime.BattleRetentionRules
  export slaydemo.backend.battle.services.runtime.BattleRuntimeCatalog
  export slaydemo.backend.battle.services.runtime.BattleRuntimeFinalizationRules
  export slaydemo.backend.battle.services.runtime.BattleRuntimeFinishRules
  export slaydemo.backend.battle.services.runtime.BattleRuntimeStepRules
  export slaydemo.backend.battle.services.runtime.BattleTimeRules
  export slaydemo.backend.battle.services.session.BattleCommandAcceptanceFactory
  export slaydemo.backend.battle.services.session.BattleCommandApplicationRules
  export slaydemo.backend.battle.services.session.BattleCommandOwnership
  export slaydemo.backend.battle.services.session.BattleCommandSubmitError
  export slaydemo.backend.battle.services.session.BattleFailureMessageFormatter
  export slaydemo.backend.battle.services.session.BattleIdGenerator
  export slaydemo.backend.battle.services.session.BattleRoomFinishedNotification
  export slaydemo.backend.battle.services.session.BattleSessionLookup
  export slaydemo.backend.battle.services.session.BattleSessionSeed
  export slaydemo.backend.battle.services.session.BattleSessionStateFactory
  export slaydemo.backend.battle.services.session.BattleStateReadError
  export slaydemo.backend.battle.services.session.BattleStateService
  export slaydemo.backend.battle.services.session.BattleStoredBattleAdvanceResult
  export slaydemo.backend.battle.services.session.BattleStoredBattleAdvanceRules
  export slaydemo.backend.battle.services.session.BattleStoredBattleInitializationRules
  export slaydemo.backend.battle.services.session.CommandSubmission
  export slaydemo.backend.battle.services.session.InMemoryBattleStateService
  export slaydemo.backend.battle.services.session.RandomBattleIdGenerator
  export slaydemo.backend.battle.services.session.StateRead
  export slaydemo.backend.battle.services.session.StoredBattle
  export slaydemo.backend.battle.services.world.ArenaObstacle
  export slaydemo.backend.battle.services.world.ArenaObstacleKind
  export slaydemo.backend.battle.services.world.BattleArenaCatalog
  export slaydemo.backend.battle.services.world.BattleArenaCollision
  export slaydemo.backend.battle.services.world.BattleGeometry
  export slaydemo.backend.battle.services.world.BattleInitialLayout
  export slaydemo.backend.battle.services.world.BattleMotionRules
  export slaydemo.backend.battle.services.world.BattleMovementCatalog
  export slaydemo.backend.battle.services.world.BattleMovementSpeed
  export slaydemo.backend.battle.services.world.BattleSlowFactor
  export slaydemo.backend.battle.services.world.BattleStaminaRatePerSecond
}
